services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\AcademicPersons\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*.php'

  FGTCLB\AcademicPersons\Domain\Model\Dto\DemandInterface:
    alias: FGTCLB\AcademicPersons\Domain\Model\Dto\ProfileDemand
    public: true

  FGTCLB\AcademicPersons\Settings\AcademicPersonsSettings:
    public: true
    factory:
      - '@FGTCLB\AcademicPersons\Settings\AcademicPersonsSettingsFactory'
      - 'get'

  FGTCLB\AcademicPersons\Command\CreateProfilesCommand:
    tags:
      - name: console.command
        command: 'academic:createprofiles'
        description: 'This command create profiles for all frontend users that do not have a profile yet but should have one.'

  FGTCLB\AcademicPersons\Command\UpdateProfilesCommand:
    tags:
      - name: console.command
        command: 'academic:updateprofiles'
        description: 'This command updates profiles for all frontend users that have a profile.'

