services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\AcademicBase\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
#      - '../Classes/Core12/*'
#      - '../Classes/Core13/*'

  # @internal not part of public API
  academic-base.serializer:
    class: Symfony\Component\Serializer\SerializerInterface
    factory: '@FGTCLB\AcademicBase\Factory\SerializerFactory'

  # @internal not part of public API
  FGTCLB\AcademicBase\Extbase\Property\TypeConverter\FileUploadConverter:
    tags:
      - name: extbase.type_converter
        priority: 10
        target: TYPO3\CMS\Extbase\Domain\Model\FileReference
        sources: array

