services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

    FGTCLB\AcademicContacts4pages\:
      resource: '../Classes'
      exclude:
        - '../Classes/Domain/Model'
